#!/usr/bin/env node
import crypto from "node:crypto"
import fs from "node:fs"
import path from "node:path"
import process from "node:process"
import { fileURLToPath } from "node:url"

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const RULE_DIR = path.join(ROOT, "docs", "ai", "rules")
const CHECK = process.argv.includes("--check")
const NEXT_BEGIN = "<!-- BEGIN:nextjs-agent-rules -->"
const NEXT_END = "<!-- END:nextjs-agent-rules -->"
const COURSE_BEGIN = "<!-- BEGIN:course-agent-rules -->"
const COURSE_END = "<!-- END:course-agent-rules -->"

const defaultNextBlock = `${NEXT_BEGIN}
# Next.js version-matched documentation

Before writing Next.js code, inspect the installed documentation under \`node_modules/next/dist/docs/\`. Prefer those files over remembered or generic snippets. Preserve this managed block when refreshing framework-generated rules.
${NEXT_END}`

function normalize(value) {
  return value.replace(/\r\n/g, "\n").trimEnd() + "\n"
}

function readFragments() {
  const names = fs.readdirSync(RULE_DIR).filter((name) => name.endsWith(".md")).sort()
  if (names.length === 0) throw new Error(`No rule fragments in ${RULE_DIR}`)
  return names.map((name) => fs.readFileSync(path.join(RULE_DIR, name), "utf8").trim()).join("\n\n")
}

function existingNextBlock() {
  const target = path.join(ROOT, "AGENTS.md")
  if (!fs.existsSync(target)) return defaultNextBlock
  const current = fs.readFileSync(target, "utf8")
  const pattern = new RegExp(`${NEXT_BEGIN}[\\s\\S]*?${NEXT_END}`)
  return current.match(pattern)?.[0] ?? defaultNextBlock
}

function generatedHeader(hash) {
  return `<!-- GENERATED by scripts/agents-sync.mjs; source-sha256: ${hash}; do not edit this adapter directly. -->`
}

const rules = readFragments()
const hash = crypto.createHash("sha256").update(rules).digest("hex").slice(0, 16)
const nextBlock = existingNextBlock()
const courseBlock = `${COURSE_BEGIN}\n${generatedHeader(hash)}\n\n${rules}\n${COURSE_END}`
const agents = normalize(`${nextBlock}\n\n${courseBlock}`)
const adapterBody = normalize(`${generatedHeader(hash)}\n\n${rules}`)

const outputs = new Map([
  ["AGENTS.md", agents],
  ["CLAUDE.md", normalize("@AGENTS.md")],
  ["GEMINI.md", normalize("@AGENTS.md")],
  [".github/copilot-instructions.md", adapterBody],
  [".github/instructions/nextjs.instructions.md", normalize(`---\napplyTo: "**/*.{ts,tsx,js,jsx,mjs,cjs}"\n---\n\n${generatedHeader(hash)}\n\n${rules}`)],
  [".cursor/rules/project.mdc", normalize(`---\ndescription: Atlas Workspace canonical project rules\nalwaysApply: true\n---\n\n${generatedHeader(hash)}\n\n${rules}`)],
  [".claude/rules/project.md", adapterBody],
  [".windsurf/rules/project.md", adapterBody],
  [".zed/rules/project.md", adapterBody],
])

const drift = []
for (const [relative, expected] of outputs) {
  const target = path.join(ROOT, relative)
  const actual = fs.existsSync(target) ? normalize(fs.readFileSync(target, "utf8")) : null
  if (CHECK) {
    if (actual !== expected) drift.push(relative)
  } else {
    fs.mkdirSync(path.dirname(target), { recursive: true })
    fs.writeFileSync(target, expected, "utf8")
    console.log(`updated ${relative}`)
  }
}

if (CHECK && drift.length > 0) {
  console.error(`Agent instruction drift: ${drift.join(", ")}`)
  console.error("Run: pnpm agents:sync, then review and commit the generated diff.")
  process.exit(1)
}
if (CHECK) console.log(`Agent adapters OK; source hash ${hash}`)
